### ISSUE TITLE
[Bug] Admin Stats for WHMCS v8 not Show order and ticket

### ISSUE THREAD

**Issue by maisonmdsgreen** [Katamaze/WHMCS-Free-Scripts#11]
Hi Admin Stats for WHMCS v8 not Show order and ticket is normal?

![whmcsv8](https://user-images.githubusercontent.com/11423362/97554790-0abf8d00-19b6-11eb-82a3-0c88c1593938.JPG)

Thanks
Maison

**Comment by Kian987** [comment]
The widget shows pending invoices, orders and tickets. In other words if there are no pending orders, it shows just invoices and tickets. If there's nothing "pending" the widget disappears.

Can you confirm me that there are no pending orders and tickets awaiting reply?

**Comment by Kian987** [comment]
Also make sure you're using the [latest version](https://github.com/Katamaze/WHMCS-Free-Scripts/blob/master/hooks/AdminStatsForWHMCSv8.php) of the script. I updated it 16 days ago.

**Comment by maisonmdsgreen** [comment]
Thanks update

Yes, I am using the latest version, yes when there is an open ticket it shows, it is because I saw an image of you that even with zero ticket it showed. It would be good in this case depending on what you have opened to remove that white space on the side.

![whmcsv8](https://user-images.githubusercontent.com/11423362/97600809-35c2d480-19e8-11eb-8823-8b22ae50f162.JPG)

You imagem show 0 ticket

![image](https://user-images.githubusercontent.com/11423362/97600901-50954900-19e8-11eb-9579-c8de708c47c5.png)

Thanks

**Comment by Kian987** [comment]
I [updated the script](https://github.com/Katamaze/WHMCS-Free-Scripts/blob/master/README.md#admin-stats-for-whmcs-v8). There's now a new variable named `$showZero` that allows to decide if you want to show or hide "zero" elements.

**Comment by maisonmdsgreen** [comment]
In this case, even if everyone has zero, will it show the notification in the corner or should it disappear?

Thanks

**Comment by Kian987** [comment]
I can't reproduce it on my WHMCS.

Basically the following line checks if there's at least one pending order, invoice or ticket.

`if (!$ordersTotal AND !$invoicesTotal AND !$ticketsTotal): return; endif;`

If all conditions are false it `return;` interrupting the action hook before it starts injecting statistics in WHMCS. Anyway you can debug this by temporarily placing the following code right before the code I just posted.

`echo 'Orders->' . $ordersTotal . ' | Invoices->' . $invoicesTotal . ' | Tickets->' . $ticketsTotal;
 die();`

Let me know what it prints on screen.

**Comment by maisonmdsgreen** [comment]
Sorry for the delay, more is working 100% as expected.
