### ISSUE TITLE
[Bug] Auto-Terminate Free Trials After X Minutes

### ISSUE THREAD

**Issue by metallicats** [Katamaze/WHMCS-Free-Scripts#12]
I was able to set it for  2, 5 and 18 mins and it works flawlessly but when I tried it for 180 minutes it wouldn't suspend. The cron is set every 5 mins and is working fine. I have 3 products set.

Are there any logs to check if it actually tried suspending on the 180-minute mark? 

What's puzzling is why it worked on 2, 5 and 18 mins and not 180.

Will try other time frames to verify and will post back here.

* WHMCS [7.10.2]
* PHP [eg. 7.4.3]

Thanks!

**Comment by Kian987** [comment]
> Are there any logs to check if it actually tried suspending on the 180-minute mark?

Yes, the hook logs when it terminates/suspends services in **Utilities > Logs > Activity Log** as follows.

![whmcs-terminate-trial](https://user-images.githubusercontent.com/68689332/97619773-eb117e80-1a20-11eb-975e-416a9724a32b.png)

But I suspect you won't find anything as the log triggers only when terminate/suspend completes successfully. If so, let me know so that I can investigate further.

**Comment by metallicats** [comment]
Hi Kian thanks for the quick reply.

I did some tests again and yes, it's not logging any error when it fails but it registers fine in **Activity Log** when it works.

Is it not changing the time of the original order when it suspends? 

This is the exact sequence I did the tests. You will notice that it's consistently working for 30 mins or less but never really get past an hour.
I've tested it with a single 4-hour old order.

20 mins = ok
25 mins = ok
31 mins = ok
45 mins = fail
35 mins = fail
31 mins = ok
35 mins = ok
60 mins = fail
45 mins = fail
35 mins = fail
31 mins = fail
20 mins = ok
31 mins = ok
45 mins = fail
25 mins = ok
45 mins = ok
60 mins = fail

**Comment by Kian987** [comment]
Thanks. I managed to find the source of the problem. I'll need to change the script. Please wait.

**Comment by Kian987** [comment]
Okay, use the [upated version](https://github.com/Katamaze/WHMCS-Free-Scripts/blob/master/hooks/AutoTerminateFreeTrialsAfterXMinutes.php) of the action hook. It should work now.

**Comment by metallicats** [comment]
Hi Kian, I just used the new code and it worked like a charm (180 minutes). Thank you for keeping this great work updated.

Cheers!

**Comment by mihaianton035** [comment]
> Hi Kian, I just used the new code and it worked like a charm (180 minutes). Thank you for keeping this great work updated.
> 
> Cheers!

does it still work? I tried and none of the codes work, what must be made to work or must be put somewhere specific?
