### ISSUE TITLE
[Feature Request] Conditional Support Departments

### ISSUE THREAD

**Issue by marbman21** [Katamaze/WHMCS-Free-Scripts#15]
I am looking for a module to be able to restrict the support departments the client can see based on the products they have. So lets say unless they have a VPS service (I understand service ids and can work off that) then they will be able to see a hidden support department, but the regular support department that is usually available, would be hidden. 

Although if they have multiple services, say web hosting and VPS, this might cause a conflict and both support departments would show. So I am not sure how to work around that, but maybe you would have a better idea.

Thanks for any consideration on this.

**Comment by Kian987** [comment]
[Here](https://github.com/Katamaze/WHMCS-Free-Scripts/blob/master/README.md#conditional-support-departments) you go.
