### ISSUE TITLE
[Feature Request] Host Image Login button Service 

### ISSUE THREAD

**Issue by maisonmdsgreen** [Katamaze/WHMCS-Free-Scripts#7]
Is possible host image cPanel Plesk button? https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#cpanel--plesk-login-button-in-my-services

`templates/{$template}/img/katamaze_autologin/{$kt_autologin[$service.id]->type}.png`

Thanks

**Comment by Kian987** [comment]
I didn't catch that :worried: Can you clarify that for me?

**Comment by maisonmdsgreen** [comment]
You have upload icons below?

![icons](https://user-images.githubusercontent.com/11423362/94980458-4fafeb00-0500-11eb-8fb3-420e6d3b89a9.JPG)

**Comment by Kian987** [comment]
True, icons are not included. I need to find a way to include them on Github. In the meantime I attached the images in the zip:

1. [Download](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/files/5320899/katamaze_autologin.zip) the zip
2. Unizp it
3. Upload `katamaze_autologin` directory in `templates/{YOUR_TEMPLATE}/img/` path

**Comment by maisonmdsgreen** [comment]
Thanks @Kian987 

Is the border blue around the image is made via css?

**Comment by Kian987** [comment]
Yes, it's a simple [Bootstrap Button](https://getbootstrap.com/docs/4.0/components/buttons/) with image inside.
