### ISSUE TITLE
[Feature Request] One-click order just with email and name

### ISSUE THREAD

**Issue by Kian987** [Katamaze/WHMCS-Free-Scripts#8]
Simplified registration page with the following features:

- Register just with email & name
- Automatically place order with specific product IDs
- Verification code (optional) based on a fixed array
- Move clients to specific WHMCS client group (optional)

**Comment by helmuc** [comment]
Registration fields:
1) First name
2) Last name
3) email
4) primary domain (adding their own domain)
5) Promotional code (unique/preset)

This is a simplified order form for new users at our WHMCS website (hostmaria.com)
