### ISSUE TITLE
[Feature Request] AdminStatsForWHMCSv8.php All Pages Admin

### ISSUE THREAD

**Issue by maisonmdsgreen** [Katamaze/WHMCS-Free-Scripts#9]
It would be nice for him to appear on every page. Not just in the initial

Thanks

**Comment by Kian987** [comment]
That's true 👍 I will update the script and let you know when it's ready.

**Comment by Kian987** [comment]
The hook as been [updated](https://github.com/Katamaze/WHMCS-Free-Scripts/blob/master/hooks/AdminStatsForWHMCSv8.php). Now it shows on all pages moreover we fixed a couple of bugs:

* Inverted icons for tickets & invoices
* Incorrect countings for tickets and overdue invoices 
* Some links not opening
